(define (problem BW-rand-8)
(:domain blocksworld-4ops)
(:requirements :action-costs :strips :typing)
(:objects b1 b2 b3 b4 b5 b6 b7 b8 )
(:init
    (= (total-cost) 0.0)
    (arm-empty)
    (on b1 b3)
    (on-table b2)
    (on b3 b8)
    (on b4 b6)
    (on b5 b7)
    (on b6 b1)
    (on b7 b4)
    (on b8 b2)
    (clear b5)
)
(:goal
    (and
    (on b3 b7)
    (on b4 b2)
    (on b5 b1)
    (on b6 b4)
    (on b7 b8)
    (on b8 b6)
    )
)
(:metric minimize (total-cost))
)